#Reading the dataset from the csv file
dataset <- read.csv("/Users/AditiGoyal/Desktop/Mine/ML/datasets/pca.csv")

#Binding the variable with the R environment so that we can access them with the name directly
attach(dataset)

#Displaying names of the features in the dataset
names(dataset)

#Checking if all the features are numnerical or not
#If not the we have to convert them into numerical value using dummies library
str(dataset)

#Selecting the set of features to be normalized to be used to generate PC
X <- cbind(Ag, Mining, Constr, Manuf, Manuf_nd, Transp, Comm, Energy, TradeW, TradeR, RE, Services, Govt)
summary(X)
cor(X)

#Generation of principal components
pcal <- princomp(X ,scores = TRUE , cor = TRUE)

#To show all the variable that are generated by PCA
names(pcal)

#different values are displayed
# 1.Mean of the variables that are used for normalization 
pcal$center

# 2. Standard Deviation of the variables that are used for normalization 
pcal$scale

# 3. Loading of the Princpal components(Value of PHI)
pcal$loadings[1:5,1:4]

# 4. Principal Component values
dim(pcal$scores) #50*13 => 50 Obs and 13 PC are generated

#Giving the propoetionof variance in each PC
summary(pcal)

#Showing the eigenvalues , value of PHI
loadings(pcal)

#calculating variance manually
std_dev <- pcal$sdev
std_var <- std_dev^2
prop_varec <- std_var / sum(std_var)

#Plotting graph to see no. of PC to take into account 
plot(pcal)
plot(pcal,xlab="PricipalComponent",ylab="Proportion of Variance Explained",type="b",main="Screen Plot")
screeplot(pcal,type="line",main="Screen Plot")
plot(cumsum(prop_varec))

biplot(pcal,choices = c(1,2))
